version: '3'

services:
    website:
        build: 
          context: .
          dockerfile: .docker/website/Dockerfile
        container_name: sf4_apache
        ports:
          - 80:80
        depends_on:
          - mysql  

    mysql:
        build: .docker/data
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf4_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: spf_db
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4 

    phpmyadmin:
        build: .docker/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql